import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { redirect } from "next/navigation"
import { auth } from "../auth"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const session = await auth()
  // if (!session?.user) {
  //   redirect("/api/auth/signin")
  // }
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
